# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact to deploy'
        required: true
        type: string
    secrets:
      PUBLISH_PROFILE:
        description: 'Azure publish profile for deployment'
        required: true
  workflow_dispatch:
    
env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:          
  deploy-dev:
    runs-on: windows-latest
#    environment: 
#      name: dev
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./output        
      - name: Deploy to Azure Functions (Staging)
        uses: Azure/functions-action@v1
        with:
          app-name: 'ant-test-func1'
          slot-name: 'Production' # or your staging slot
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
      # TODO slot swap
  
  deploy-staging:
    needs: deploy-dev
    runs-on: windows-latest
    environment: 
      name: staging
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./output
      - name: Deploy to Azure Functions (Production)
        uses: Azure/functions-action@v1
        with:
          app-name: 'ant-test-func1'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        # TODO slot swap
        
  deploy-prod:
    needs: deploy-staging
    runs-on: windows-latest
    environment: 
      name: prod
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./output
      - name: Deploy to Azure Functions (Production)
        uses: Azure/functions-action@v1
        with:
          app-name: 'ant-test-func1'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        # TODO slot swap

  deploy-prod2:
    needs: deploy-staging
    runs-on: windows-latest
    environment: 
      name: prod2
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./output
      - name: Deploy to Azure Functions (Production)
        uses: Azure/functions-action@v1
        with:
          app-name: 'ant-test-func1'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        # TODO slot swap