name: Terraform Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tf_version:
        required: false
        type: string
        default: '1.5.0'
      tf_working_dir:
        required: false
        type: string
        default: './infrastructure'
      action:
        required: true
        type: string
        description: 'Either "plan" or "apply"'
    outputs:
      plan_status:
        description: 'Status of the plan step'
        value: ${{ jobs.terraform.outputs.plan_status }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      plan_status: ${{ steps.plan.outcome }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      
#      - name: 'Setup Terraform'
#        uses: hashicorp/setup-terraform@v2
#        with:
#          terraform_version: ${{ inputs.tf_version }}
#      
#      - name: 'Terraform Init'
#        working-directory: ${{ inputs.tf_working_dir }}
#        run: terraform init
#      
#      - name: 'Terraform Plan'
#        if: inputs.action == 'plan'
#        id: plan
#        working-directory: ${{ inputs.tf_working_dir }}
#        run: terraform plan -var-file="environments/${{ inputs.environment }}.tfvars" -out=${{ inputs.environment }}.tfplan
#      
#      - name: 'Terraform Apply'
#        if: inputs.action == 'apply'
#        working-directory: ${{ inputs.tf_working_dir }}
#        run: terraform apply -var-file="environments/${{ inputs.environment }}.tfvars" -auto-approve