name: Infrastructure Pipeline
run-name: Infrastructure Pipeline ${{ github.run_number }} (${{ github.ref_name }})

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  plan-dev:
    runs-on: ubuntu-latest
    outputs:
      plan_status: ${{ steps.terraform.outputs.plan_status }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Run Terraform Plan'
        id: terraform
        uses: ./.github/actions/terraform
        with:
          environment: dev
          action: plan

  plan-stage:
    runs-on: ubuntu-latest
    outputs:
      plan_status: ${{ steps.terraform.outputs.plan_status }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Run Terraform Plan'
        id: terraform
        uses: ./.github/actions/terraform
        with:
          environment: staging
          action: plan

  plan-prod:
    runs-on: ubuntu-latest
    outputs:
      plan_status: ${{ steps.terraform.outputs.plan_status }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Run Terraform Plan'
        id: terraform
        uses: ./.github/actions/terraform
        with:
          environment: prod
          action: plan

  apply-dev:
    needs: plan-dev
    if: github.event_name != 'pull_request' && needs.plan-dev.outputs.plan_status == 'success'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Run Terraform Apply'
        uses: ./.github/actions/terraform
        with:
          environment: dev-approve
          action: apply

  apply-stage:
    needs: [plan-stage, apply-dev]
    if: github.event_name != 'pull_request' && needs.plan-stage.outputs.plan_status == 'success'
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Run Terraform Apply'
        uses: ./.github/actions/terraform
        with:
          environment: stage
          action: apply

  apply-prod:
    needs: [plan-prod, apply-stage]
    if: github.event_name != 'pull_request' && needs.plan-prod.outputs.plan_status == 'success'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Run Terraform Apply'
        uses: ./.github/actions/terraform
        with:
          environment: prod
          action: apply