name: Infrastructure Pipeline
run-name: Infrastructure Pipeline ${{ github.run_number }} (${{ github.ref_name }})

on:
  push:
    branches:
      - main
#    paths:
#      - 'infrastructure/**'
  pull_request:
    branches:
      - main
#    paths:
#      - 'infrastructure/**'
  workflow_dispatch:


jobs:
  plan-dev:
    uses: ./infra_template.yml
    with:
      environment: dev
      action: plan

  plan-stage:
    uses: ./infra_template.yml
    with:
      environment: stage
      action: plan

  plan-prod:
    uses: ./infra_template.yml
    with:
      environment: prod
      action: plan

  apply-dev:
    needs: plan-dev
    if: github.event_name != 'pull_request' && needs.plan-dev.outputs.plan_status == 'success'
    uses: ./infra_template.yml
    with:
      environment: dev
      action: apply

  apply-stage:
    needs: plan-stage
    if: github.event_name != 'pull_request' && needs.plan-stage.outputs.plan_status == 'success'
    uses: ./infra_template.yml
    with:
      environment: stage
      action: apply

  apply-prod:
    needs: plan-prod
    if: github.event_name != 'pull_request' && needs.plan-prod.outputs.plan_status == 'success'
    uses: ./infra_template.yml
    with:
      environment: prod
      action: apply