# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - ant-test-func1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-build
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output

          
  deploy-dev:
    needs: build
    runs-on: windows-latest
    environment: 
      name: dev
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
      
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: function-build
          path: ./output        
          
      - name: Deploy to Azure Functions (Staging)
        uses: Azure/functions-action@v1
        with:
          app-name: 'ant-test-func1'
          slot-name: 'Production' # or your staging slot
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C6ADCD3FF2954889AAEE9458525567A2 }}
      # TODO slot swap
  
  deploy-staging:
    needs: deploy-dev
    if: ${{ always() }}
    runs-on: windows-latest
    environment: 
      name: staging
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
      
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: function-build
          path: ./output
      - name: Deploy to Azure Functions (Production)
        uses: Azure/functions-action@v1
        with:
          app-name: 'ant-test-func1'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C6ADCD3FF2954889AAEE9458525567A2 }}
        # TODO slot swap
        
  deploy-prod:
    needs: deploy-staging
    runs-on: windows-latest
    environment: 
      name: prod
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
      
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: function-build
          path: ./output
      - name: Deploy to Azure Functions (Production)
        uses: Azure/functions-action@v1
        with:
          app-name: 'ant-test-func1'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C6ADCD3FF2954889AAEE9458525567A2 }}
        # TODO slot swap

  deploy-prod2:
    needs: deploy-staging
    runs-on: windows-latest
    environment: 
      name: prod2
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4
      
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: function-build
          path: ./output
      - name: Deploy to Azure Functions (Production)
        uses: Azure/functions-action@v1
        with:
          app-name: 'ant-test-func1'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C6ADCD3FF2954889AAEE9458525567A2 }}
        # TODO slot swap


